import {
  Briefcase,
  TrendingUp,
  Gift,
  Coins,
  HandCoins,
  PiggyBank,
  ShoppingCart,
  ShoppingBag,
  Home,
  Car,
  Bus,
  Fuel,
  Utensils,
  Coffee,
  Pizza,
  Heart,
  Stethoscope,
  Pill,
  GraduationCap,
  BookOpen,
  Dumbbell,
  Gamepad2,
  Tv,
  Music,
  Plane,
  Shirt,
  Smartphone,
  Wifi,
  Zap,
  Droplets,
  Dog,
  Baby,
  Wrench,
  Receipt,
  Banknote,
  Tag,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const CATEGORY_ICONS: { name: string; label: string }[] = [
  // Receitas
  { name: "Briefcase", label: "Salário" },
  { name: "TrendingUp", label: "Investimento" },
  { name: "Gift", label: "Presente" },
  { name: "Coins", label: "Moedas" },
  { name: "HandCoins", label: "Freelance" },
  { name: "PiggyBank", label: "Poupança" },

  // Despesas gerais
  { name: "ShoppingCart", label: "Compras" },
  { name: "ShoppingBag", label: "Shopping" },
  { name: "Home", label: "Moradia" },
  { name: "Car", label: "Transporte" },
  { name: "Bus", label: "Ônibus" },
  { name: "Fuel", label: "Combustível" },
  { name: "Utensils", label: "Alimentação" },
  { name: "Coffee", label: "Café" },
  { name: "Pizza", label: "Fast Food" },
  { name: "Heart", label: "Saúde" },
  { name: "Stethoscope", label: "Médico" },
  { name: "Pill", label: "Farmácia" },
  { name: "GraduationCap", label: "Educação" },
  { name: "BookOpen", label: "Livros" },
  { name: "Dumbbell", label: "Academia" },
  { name: "Gamepad2", label: "Lazer" },
  { name: "Tv", label: "Streaming" },
  { name: "Music", label: "Música" },
  { name: "Plane", label: "Viagem" },
  { name: "Shirt", label: "Vestuário" },
  { name: "Smartphone", label: "Tecnologia" },
  { name: "Wifi", label: "Internet" },
  { name: "Zap", label: "Energia" },
  { name: "Droplets", label: "Água" },
  { name: "Dog", label: "Pet" },
  { name: "Baby", label: "Filhos" },
  { name: "Wrench", label: "Manutenção" },
  { name: "Receipt", label: "Impostos" },
  { name: "Banknote", label: "Outros" },
  { name: "Tag", label: "Geral" },
];

export const DEFAULT_CATEGORY_ICON = "Tag";

const ICON_MAP: Record<string, LucideIcon> = {
  Briefcase,
  TrendingUp,
  Gift,
  Coins,
  HandCoins,
  PiggyBank,
  ShoppingCart,
  ShoppingBag,
  Home,
  Car,
  Bus,
  Fuel,
  Utensils,
  Coffee,
  Pizza,
  Heart,
  Stethoscope,
  Pill,
  GraduationCap,
  BookOpen,
  Dumbbell,
  Gamepad2,
  Tv,
  Music,
  Plane,
  Shirt,
  Smartphone,
  Wifi,
  Zap,
  Droplets,
  Dog,
  Baby,
  Wrench,
  Receipt,
  Banknote,
  Tag,
};

export function getCategoryIconComponent(iconName: string): LucideIcon {
  return ICON_MAP[iconName] ?? Tag;
}
